In [1]:
import tensorflow
import tensorflow as tf 
import numpy as np


#### Initilization of Tensors

In [2]:
a = tf.constant(1)
print(a)

tf.Tensor(1, shape=(), dtype=int32)


In [5]:
a = tf.constant(1 , dtype = tf.float32)
print(a)

tf.Tensor(1.0, shape=(), dtype=float32)


In [6]:
a = tf.constant(1 , shape = (1,1) , dtype = tf.float32)
print(a)

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


In [7]:
a = tf.constant(1 , shape = (2,2) , dtype = tf.int32)
print(a)

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [11]:
a = tf.constant([[1,2,3] , [4,5,6]] , dtype = tf.float32)
print(a)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [12]:
a = tf.ones((3,3))
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [16]:
a = tf.zeros((3,3) , dtype = tf.int32)
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [17]:
a = tf.zeros((3,3))
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [26]:
a = tf.eye(3,dtype=tf.int32)
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])>

In [31]:
a = tf.random.normal((3,3) , mean = 0 , stddev = 1)
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.94084954, -1.1260958 ,  1.9347833 ],
       [ 0.45865726, -0.7682472 ,  0.18526925],
       [ 0.28243178,  0.3205698 , -0.78498596]], dtype=float32)>

In [33]:
a = tf.random.uniform((1,3),minval = 0,maxval = 1)
a

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.8455701 , 0.10463369, 0.18534839]], dtype=float32)>

In [37]:
a = tf.range(1,10)
a

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [38]:
a = tf.range(start = 1 , limit = 10 , delta = 2)
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [40]:
a = tf.range(1,10,2 , dtype = tf.float32)
a

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 3., 5., 7., 9.], dtype=float32)>

In [41]:
a = tf.range(1,10,2 , dtype = tf.int32)
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [43]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
c = tf.add(a,b)
print(c)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [44]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
c = a + b
print(c)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [46]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
c = tf.subtract(a,b)
print(c)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [47]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
c = a - b
print(c)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [48]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
c = tf.divide(a,b)
print(c)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [49]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
c = a / b
print(c)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [50]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
c = tf.multiply(a,b)
print(c)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [51]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
c = a * b
print(c)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [53]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
c = tf.tensordot(a,b,axes = 1)
print(c)

tf.Tensor(32, shape=(), dtype=int32)


In [56]:
a = tf.constant([0,1,2,3,4,5])
print(a[4:])

tf.Tensor([4 5], shape=(2,), dtype=int32)


In [57]:
a = tf.range(1,10)
print(a[5:])

tf.Tensor([6 7 8 9], shape=(4,), dtype=int32)


In [58]:
a = tf.range(1,10)
print(a[2:8:2])

tf.Tensor([3 5 7], shape=(3,), dtype=int32)


In [59]:
a = tf.range(1,10)
print(a[::-1])

tf.Tensor([9 8 7 6 5 4 3 2 1], shape=(9,), dtype=int32)


In [60]:
a = tf.constant([[1,2,3],
                [4,5,6],
                [7,8,9]])
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [62]:
print(a[0 , :])

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [63]:
print(a[1 , 1])

tf.Tensor(5, shape=(), dtype=int32)


In [64]:
print(a[1:2 , 1:2])

tf.Tensor([[5]], shape=(1, 1), dtype=int32)


#### Reshaping

In [68]:
a = tf.range(9)
a = tf.reshape(a , (3,3))
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [70]:
a = tf.range(1,61)
a = tf.reshape(a , (5,2,6))
a

<tf.Tensor: shape=(5, 2, 6), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]],

       [[37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48]],

       [[49, 50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59, 60]]])>

In [79]:
a = tf.range(9)
a = tf.reshape(a , (3,3))
a = tf.transpose(a)
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>

In [78]:
a = tf.range(9)
a = tf.reshape(a , (3,3))
a = tf.transpose(a, perm = [1,0])  # perm is for using in multiple dimensions 
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>